 ## Site settings
title: Aaron Prill
description: Sr. Software Engineer at Tyler Technologies since 2004.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://prillcode.github.io" # the base hostname & protocol for your site, e.g. http://example.com

## Theme
remote_theme: just-the-docs/just-the-docs

## No search bar at the top
search_enabled: false

# Add anchors for every heading on a page
heading_anchors: true

# Aux Links in upper right
aux_links:
  "Prof. Github (prillcode)":
    - "//github.com/prillcode"
  "Personal Github (prilldev)":
    - "//github.com/prilldev"

aux_links_new_tab: true

